// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.11.1.

// ignore_for_file: unused_import, unused_element, unnecessary_import, duplicate_ignore, invalid_use_of_internal_member, annotate_overrides, non_constant_identifier_names, curly_braces_in_flow_control_structures, prefer_const_literals_to_create_immutables, unused_field

import 'api.dart';
import 'dart:async';
import 'dart:convert';
import 'frb_generated.dart';
import 'frb_generated.io.dart'
    if (dart.library.js_interop) 'frb_generated.web.dart';
import 'lib.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

/// Main entrypoint of the Rust API
class AudioPalette extends BaseEntrypoint<AudioPaletteApi, AudioPaletteApiImpl,
    AudioPaletteWire> {
  @internal
  static final instance = AudioPalette._();

  AudioPalette._();

  /// Initialize flutter_rust_bridge
  static Future<void> init({
    AudioPaletteApi? api,
    BaseHandler? handler,
    ExternalLibrary? externalLibrary,
    bool forceSameCodegenVersion = true,
  }) async {
    await instance.initImpl(
      api: api,
      handler: handler,
      externalLibrary: externalLibrary,
      forceSameCodegenVersion: forceSameCodegenVersion,
    );
  }

  /// Initialize flutter_rust_bridge in mock mode.
  /// No libraries for FFI are loaded.
  static void initMock({
    required AudioPaletteApi api,
  }) {
    instance.initMockImpl(
      api: api,
    );
  }

  /// Dispose flutter_rust_bridge
  ///
  /// The call to this function is optional, since flutter_rust_bridge (and everything else)
  /// is automatically disposed when the app stops.
  static void dispose() => instance.disposeImpl();

  @override
  ApiImplConstructor<AudioPaletteApiImpl, AudioPaletteWire>
      get apiImplConstructor => AudioPaletteApiImpl.new;

  @override
  WireConstructor<AudioPaletteWire> get wireConstructor =>
      AudioPaletteWire.fromExternalLibrary;

  @override
  Future<void> executeRustInitializers() async {}

  @override
  ExternalLibraryLoaderConfig get defaultExternalLibraryLoaderConfig =>
      kDefaultExternalLibraryLoaderConfig;

  @override
  String get codegenVersion => '2.11.1';

  @override
  int get rustContentHash => -663634271;

  static const kDefaultExternalLibraryLoaderConfig =
      ExternalLibraryLoaderConfig(
    stem: 'audio_palette',
    ioDirectory: 'rust/target/release/',
    webPrefix: 'pkg/',
  );
}

abstract class AudioPaletteApi extends BaseApi {
  Future<PlatformInt64> crateApiAddSound({required String filepath});

  double crateApiComputeSimilarity(
      {required String fp1Path, required String fp2Path});

  Future<void> crateApiExportToCsv(
      {required List<MatchResult> matches, required String outputPath});

  Future<void> crateApiExportToMarkers(
      {required List<MatchResult> matches, required String outputPath});

  Future<void> crateApiExportToMidi(
      {required List<MatchResult> matches,
      required String outputPath,
      required int tempoBpm,
      required int baseNote});

  Future<List<MatchResult>> crateApiFindSimilar(
      {required String queryPath,
      required double threshold,
      required BigInt maxResults});

  Future<List<MatchResult>> crateApiFindSimilarFromSamples(
      {required List<double> samples,
      required int sampleRate,
      required double threshold,
      required BigInt maxResults});

  Future<List<MatchResult>> crateApiFindSimilarWithSegments(
      {required String queryPath,
      required double threshold,
      required BigInt maxResults});

  Future<List<SoundRecord>> crateApiGetAllSounds();

  Future<AudioFingerprintInfo> crateApiGetFingerprint(
      {required String filepath});

  PlatformInt64 crateApiGetSoundCount();

  void crateApiInitDatabase({required String dbPath});

  Future<void> crateApiRemoveSound({required PlatformInt64 soundId});

  Future<List<SoundRecord>> crateApiSearchSounds({required String query});
}

class AudioPaletteApiImpl extends AudioPaletteApiImplPlatform
    implements AudioPaletteApi {
  AudioPaletteApiImpl({
    required super.handler,
    required super.wire,
    required super.generalizedFrbRustBinding,
    required super.portManager,
  });

  @override
  Future<PlatformInt64> crateApiAddSound({required String filepath}) {
    return handler.executeNormal(NormalTask(
      callFfi: (port_) {
        final serializer = SseSerializer(generalizedFrbRustBinding);
        sse_encode_String(filepath, serializer);
        pdeCallFfi(generalizedFrbRustBinding, serializer,
            funcId: 1, port: port_);
      },
      codec: SseCodec(
        decodeSuccessData: sse_decode_i_64,
        decodeErrorData: sse_decode_String,
      ),
      constMeta: kCrateApiAddSoundConstMeta,
      argValues: [filepath],
      apiImpl: this,
    ));
  }

  TaskConstMeta get kCrateApiAddSoundConstMeta => const TaskConstMeta(
        debugName: "add_sound",
        argNames: ["filepath"],
      );

  @override
  double crateApiComputeSimilarity(
      {required String fp1Path, required String fp2Path}) {
    return handler.executeSync(SyncTask(
      callFfi: () {
        final serializer = SseSerializer(generalizedFrbRustBinding);
        sse_encode_String(fp1Path, serializer);
        sse_encode_String(fp2Path, serializer);
        return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 2)!;
      },
      codec: SseCodec(
        decodeSuccessData: sse_decode_f_64,
        decodeErrorData: sse_decode_String,
      ),
      constMeta: kCrateApiComputeSimilarityConstMeta,
      argValues: [fp1Path, fp2Path],
      apiImpl: this,
    ));
  }

  TaskConstMeta get kCrateApiComputeSimilarityConstMeta => const TaskConstMeta(
        debugName: "compute_similarity",
        argNames: ["fp1Path", "fp2Path"],
      );

  @override
  Future<void> crateApiExportToCsv(
      {required List<MatchResult> matches, required String outputPath}) {
    return handler.executeNormal(NormalTask(
      callFfi: (port_) {
        final serializer = SseSerializer(generalizedFrbRustBinding);
        sse_encode_list_match_result(matches, serializer);
        sse_encode_String(outputPath, serializer);
        pdeCallFfi(generalizedFrbRustBinding, serializer,
            funcId: 3, port: port_);
      },
      codec: SseCodec(
        decodeSuccessData: sse_decode_unit,
        decodeErrorData: sse_decode_String,
      ),
      constMeta: kCrateApiExportToCsvConstMeta,
      argValues: [matches, outputPath],
      apiImpl: this,
    ));
  }

  TaskConstMeta get kCrateApiExportToCsvConstMeta => const TaskConstMeta(
        debugName: "export_to_csv",
        argNames: ["matches", "outputPath"],
      );

  @override
  Future<void> crateApiExportToMarkers(
      {required List<MatchResult> matches, required String outputPath}) {
    return handler.executeNormal(NormalTask(
      callFfi: (port_) {
        final serializer = SseSerializer(generalizedFrbRustBinding);
        sse_encode_list_match_result(matches, serializer);
        sse_encode_String(outputPath, serializer);
        pdeCallFfi(generalizedFrbRustBinding, serializer,
            funcId: 4, port: port_);
      },
      codec: SseCodec(
        decodeSuccessData: sse_decode_unit,
        decodeErrorData: sse_decode_String,
      ),
      constMeta: kCrateApiExportToMarkersConstMeta,
      argValues: [matches, outputPath],
      apiImpl: this,
    ));
  }

  TaskConstMeta get kCrateApiExportToMarkersConstMeta => const TaskConstMeta(
        debugName: "export_to_markers",
        argNames: ["matches", "outputPath"],
      );

  @override
  Future<void> crateApiExportToMidi(
      {required List<MatchResult> matches,
      required String outputPath,
      required int tempoBpm,
      required int baseNote}) {
    return handler.executeNormal(NormalTask(
      callFfi: (port_) {
        final serializer = SseSerializer(generalizedFrbRustBinding);
        sse_encode_list_match_result(matches, serializer);
        sse_encode_String(outputPath, serializer);
        sse_encode_u_32(tempoBpm, serializer);
        sse_encode_u_8(baseNote, serializer);
        pdeCallFfi(generalizedFrbRustBinding, serializer,
            funcId: 5, port: port_);
      },
      codec: SseCodec(
        decodeSuccessData: sse_decode_unit,
        decodeErrorData: sse_decode_String,
      ),
      constMeta: kCrateApiExportToMidiConstMeta,
      argValues: [matches, outputPath, tempoBpm, baseNote],
      apiImpl: this,
    ));
  }

  TaskConstMeta get kCrateApiExportToMidiConstMeta => const TaskConstMeta(
        debugName: "export_to_midi",
        argNames: ["matches", "outputPath", "tempoBpm", "baseNote"],
      );

  @override
  Future<List<MatchResult>> crateApiFindSimilar(
      {required String queryPath,
      required double threshold,
      required BigInt maxResults}) {
    return handler.executeNormal(NormalTask(
      callFfi: (port_) {
        final serializer = SseSerializer(generalizedFrbRustBinding);
        sse_encode_String(queryPath, serializer);
        sse_encode_f_64(threshold, serializer);
        sse_encode_usize(maxResults, serializer);
        pdeCallFfi(generalizedFrbRustBinding, serializer,
            funcId: 6, port: port_);
      },
      codec: SseCodec(
        decodeSuccessData: sse_decode_list_match_result,
        decodeErrorData: sse_decode_String,
      ),
      constMeta: kCrateApiFindSimilarConstMeta,
      argValues: [queryPath, threshold, maxResults],
      apiImpl: this,
    ));
  }

  TaskConstMeta get kCrateApiFindSimilarConstMeta => const TaskConstMeta(
        debugName: "find_similar",
        argNames: ["queryPath", "threshold", "maxResults"],
      );

  @override
  Future<List<MatchResult>> crateApiFindSimilarFromSamples(
      {required List<double> samples,
      required int sampleRate,
      required double threshold,
      required BigInt maxResults}) {
    return handler.executeNormal(NormalTask(
      callFfi: (port_) {
        final serializer = SseSerializer(generalizedFrbRustBinding);
        sse_encode_list_prim_f_32_loose(samples, serializer);
        sse_encode_u_32(sampleRate, serializer);
        sse_encode_f_64(threshold, serializer);
        sse_encode_usize(maxResults, serializer);
        pdeCallFfi(generalizedFrbRustBinding, serializer,
            funcId: 7, port: port_);
      },
      codec: SseCodec(
        decodeSuccessData: sse_decode_list_match_result,
        decodeErrorData: sse_decode_String,
      ),
      constMeta: kCrateApiFindSimilarFromSamplesConstMeta,
      argValues: [samples, sampleRate, threshold, maxResults],
      apiImpl: this,
    ));
  }

  TaskConstMeta get kCrateApiFindSimilarFromSamplesConstMeta =>
      const TaskConstMeta(
        debugName: "find_similar_from_samples",
        argNames: ["samples", "sampleRate", "threshold", "maxResults"],
      );

  @override
  Future<List<MatchResult>> crateApiFindSimilarWithSegments(
      {required String queryPath,
      required double threshold,
      required BigInt maxResults}) {
    return handler.executeNormal(NormalTask(
      callFfi: (port_) {
        final serializer = SseSerializer(generalizedFrbRustBinding);
        sse_encode_String(queryPath, serializer);
        sse_encode_f_64(threshold, serializer);
        sse_encode_usize(maxResults, serializer);
        pdeCallFfi(generalizedFrbRustBinding, serializer,
            funcId: 8, port: port_);
      },
      codec: SseCodec(
        decodeSuccessData: sse_decode_list_match_result,
        decodeErrorData: sse_decode_String,
      ),
      constMeta: kCrateApiFindSimilarWithSegmentsConstMeta,
      argValues: [queryPath, threshold, maxResults],
      apiImpl: this,
    ));
  }

  TaskConstMeta get kCrateApiFindSimilarWithSegmentsConstMeta =>
      const TaskConstMeta(
        debugName: "find_similar_with_segments",
        argNames: ["queryPath", "threshold", "maxResults"],
      );

  @override
  Future<List<SoundRecord>> crateApiGetAllSounds() {
    return handler.executeNormal(NormalTask(
      callFfi: (port_) {
        final serializer = SseSerializer(generalizedFrbRustBinding);
        pdeCallFfi(generalizedFrbRustBinding, serializer,
            funcId: 9, port: port_);
      },
      codec: SseCodec(
        decodeSuccessData: sse_decode_list_sound_record,
        decodeErrorData: sse_decode_String,
      ),
      constMeta: kCrateApiGetAllSoundsConstMeta,
      argValues: [],
      apiImpl: this,
    ));
  }

  TaskConstMeta get kCrateApiGetAllSoundsConstMeta => const TaskConstMeta(
        debugName: "get_all_sounds",
        argNames: [],
      );

  @override
  Future<AudioFingerprintInfo> crateApiGetFingerprint(
      {required String filepath}) {
    return handler.executeNormal(NormalTask(
      callFfi: (port_) {
        final serializer = SseSerializer(generalizedFrbRustBinding);
        sse_encode_String(filepath, serializer);
        pdeCallFfi(generalizedFrbRustBinding, serializer,
            funcId: 10, port: port_);
      },
      codec: SseCodec(
        decodeSuccessData: sse_decode_audio_fingerprint_info,
        decodeErrorData: sse_decode_String,
      ),
      constMeta: kCrateApiGetFingerprintConstMeta,
      argValues: [filepath],
      apiImpl: this,
    ));
  }

  TaskConstMeta get kCrateApiGetFingerprintConstMeta => const TaskConstMeta(
        debugName: "get_fingerprint",
        argNames: ["filepath"],
      );

  @override
  PlatformInt64 crateApiGetSoundCount() {
    return handler.executeSync(SyncTask(
      callFfi: () {
        final serializer = SseSerializer(generalizedFrbRustBinding);
        return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 11)!;
      },
      codec: SseCodec(
        decodeSuccessData: sse_decode_i_64,
        decodeErrorData: sse_decode_String,
      ),
      constMeta: kCrateApiGetSoundCountConstMeta,
      argValues: [],
      apiImpl: this,
    ));
  }

  TaskConstMeta get kCrateApiGetSoundCountConstMeta => const TaskConstMeta(
        debugName: "get_sound_count",
        argNames: [],
      );

  @override
  void crateApiInitDatabase({required String dbPath}) {
    return handler.executeSync(SyncTask(
      callFfi: () {
        final serializer = SseSerializer(generalizedFrbRustBinding);
        sse_encode_String(dbPath, serializer);
        return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 12)!;
      },
      codec: SseCodec(
        decodeSuccessData: sse_decode_unit,
        decodeErrorData: sse_decode_String,
      ),
      constMeta: kCrateApiInitDatabaseConstMeta,
      argValues: [dbPath],
      apiImpl: this,
    ));
  }

  TaskConstMeta get kCrateApiInitDatabaseConstMeta => const TaskConstMeta(
        debugName: "init_database",
        argNames: ["dbPath"],
      );

  @override
  Future<void> crateApiRemoveSound({required PlatformInt64 soundId}) {
    return handler.executeNormal(NormalTask(
      callFfi: (port_) {
        final serializer = SseSerializer(generalizedFrbRustBinding);
        sse_encode_i_64(soundId, serializer);
        pdeCallFfi(generalizedFrbRustBinding, serializer,
            funcId: 13, port: port_);
      },
      codec: SseCodec(
        decodeSuccessData: sse_decode_unit,
        decodeErrorData: sse_decode_String,
      ),
      constMeta: kCrateApiRemoveSoundConstMeta,
      argValues: [soundId],
      apiImpl: this,
    ));
  }

  TaskConstMeta get kCrateApiRemoveSoundConstMeta => const TaskConstMeta(
        debugName: "remove_sound",
        argNames: ["soundId"],
      );

  @override
  Future<List<SoundRecord>> crateApiSearchSounds({required String query}) {
    return handler.executeNormal(NormalTask(
      callFfi: (port_) {
        final serializer = SseSerializer(generalizedFrbRustBinding);
        sse_encode_String(query, serializer);
        pdeCallFfi(generalizedFrbRustBinding, serializer,
            funcId: 14, port: port_);
      },
      codec: SseCodec(
        decodeSuccessData: sse_decode_list_sound_record,
        decodeErrorData: sse_decode_String,
      ),
      constMeta: kCrateApiSearchSoundsConstMeta,
      argValues: [query],
      apiImpl: this,
    ));
  }

  TaskConstMeta get kCrateApiSearchSoundsConstMeta => const TaskConstMeta(
        debugName: "search_sounds",
        argNames: ["query"],
      );

  @protected
  String dco_decode_String(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as String;
  }

  @protected
  AudioFingerprintInfo dco_decode_audio_fingerprint_info(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 6)
      throw Exception('unexpected arr length: expect 6 but see ${arr.length}');
    return AudioFingerprintInfo(
      duration: dco_decode_f_64(arr[0]),
      spectralCentroid: dco_decode_f_64(arr[1]),
      spectralBandwidth: dco_decode_f_64(arr[2]),
      spectralRolloff: dco_decode_f_64(arr[3]),
      mfccMean: dco_decode_list_prim_f_64_strict(arr[4]),
      mfccStd: dco_decode_list_prim_f_64_strict(arr[5]),
    );
  }

  @protected
  double dco_decode_f_32(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as double;
  }

  @protected
  double dco_decode_f_64(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as double;
  }

  @protected
  PlatformInt64 dco_decode_i_64(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return dcoDecodeI64(raw);
  }

  @protected
  List<MatchResult> dco_decode_list_match_result(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return (raw as List<dynamic>).map(dco_decode_match_result).toList();
  }

  @protected
  List<double> dco_decode_list_prim_f_32_loose(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as List<double>;
  }

  @protected
  Float32List dco_decode_list_prim_f_32_strict(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as Float32List;
  }

  @protected
  Float64List dco_decode_list_prim_f_64_strict(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as Float64List;
  }

  @protected
  Uint8List dco_decode_list_prim_u_8_strict(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as Uint8List;
  }

  @protected
  List<SoundRecord> dco_decode_list_sound_record(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return (raw as List<dynamic>).map(dco_decode_sound_record).toList();
  }

  @protected
  MatchResult dco_decode_match_result(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 7)
      throw Exception('unexpected arr length: expect 7 but see ${arr.length}');
    return MatchResult(
      soundId: dco_decode_i_64(arr[0]),
      filepath: dco_decode_String(arr[1]),
      filename: dco_decode_String(arr[2]),
      score: dco_decode_f_64(arr[3]),
      matchStart: dco_decode_f_64(arr[4]),
      matchEnd: dco_decode_f_64(arr[5]),
      fileDuration: dco_decode_f_64(arr[6]),
    );
  }

  @protected
  SoundRecord dco_decode_sound_record(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 8)
      throw Exception('unexpected arr length: expect 8 but see ${arr.length}');
    return SoundRecord(
      id: dco_decode_i_64(arr[0]),
      filepath: dco_decode_String(arr[1]),
      filename: dco_decode_String(arr[2]),
      duration: dco_decode_f_64(arr[3]),
      sampleRate: dco_decode_u_32(arr[4]),
      channels: dco_decode_u_16(arr[5]),
      format: dco_decode_String(arr[6]),
      dateAdded: dco_decode_String(arr[7]),
    );
  }

  @protected
  int dco_decode_u_16(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as int;
  }

  @protected
  int dco_decode_u_32(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as int;
  }

  @protected
  int dco_decode_u_8(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as int;
  }

  @protected
  void dco_decode_unit(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return;
  }

  @protected
  BigInt dco_decode_usize(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return dcoDecodeU64(raw);
  }

  @protected
  String sse_decode_String(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    final inner = sse_decode_list_prim_u_8_strict(deserializer);
    return utf8.decoder.convert(inner);
  }

  @protected
  AudioFingerprintInfo sse_decode_audio_fingerprint_info(
      SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    final var_duration = sse_decode_f_64(deserializer);
    final var_spectralCentroid = sse_decode_f_64(deserializer);
    final var_spectralBandwidth = sse_decode_f_64(deserializer);
    final var_spectralRolloff = sse_decode_f_64(deserializer);
    final var_mfccMean = sse_decode_list_prim_f_64_strict(deserializer);
    final var_mfccStd = sse_decode_list_prim_f_64_strict(deserializer);
    return AudioFingerprintInfo(
        duration: var_duration,
        spectralCentroid: var_spectralCentroid,
        spectralBandwidth: var_spectralBandwidth,
        spectralRolloff: var_spectralRolloff,
        mfccMean: var_mfccMean,
        mfccStd: var_mfccStd);
  }

  @protected
  double sse_decode_f_32(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getFloat32();
  }

  @protected
  double sse_decode_f_64(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getFloat64();
  }

  @protected
  PlatformInt64 sse_decode_i_64(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getPlatformInt64();
  }

  @protected
  List<MatchResult> sse_decode_list_match_result(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    final len_ = sse_decode_i_32(deserializer);
    final ans_ = <MatchResult>[];
    for (var idx_ = 0; idx_ < len_; ++idx_) {
      ans_.add(sse_decode_match_result(deserializer));
    }
    return ans_;
  }

  @protected
  List<double> sse_decode_list_prim_f_32_loose(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    final len_ = sse_decode_i_32(deserializer);
    return deserializer.buffer.getFloat32List(len_);
  }

  @protected
  Float32List sse_decode_list_prim_f_32_strict(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    final len_ = sse_decode_i_32(deserializer);
    return deserializer.buffer.getFloat32List(len_);
  }

  @protected
  Float64List sse_decode_list_prim_f_64_strict(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    final len_ = sse_decode_i_32(deserializer);
    return deserializer.buffer.getFloat64List(len_);
  }

  @protected
  Uint8List sse_decode_list_prim_u_8_strict(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    final len_ = sse_decode_i_32(deserializer);
    return deserializer.buffer.getUint8List(len_);
  }

  @protected
  List<SoundRecord> sse_decode_list_sound_record(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    final len_ = sse_decode_i_32(deserializer);
    final ans_ = <SoundRecord>[];
    for (var idx_ = 0; idx_ < len_; ++idx_) {
      ans_.add(sse_decode_sound_record(deserializer));
    }
    return ans_;
  }

  @protected
  MatchResult sse_decode_match_result(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    final var_soundId = sse_decode_i_64(deserializer);
    final var_filepath = sse_decode_String(deserializer);
    final var_filename = sse_decode_String(deserializer);
    final var_score = sse_decode_f_64(deserializer);
    final var_matchStart = sse_decode_f_64(deserializer);
    final var_matchEnd = sse_decode_f_64(deserializer);
    final var_fileDuration = sse_decode_f_64(deserializer);
    return MatchResult(
        soundId: var_soundId,
        filepath: var_filepath,
        filename: var_filename,
        score: var_score,
        matchStart: var_matchStart,
        matchEnd: var_matchEnd,
        fileDuration: var_fileDuration);
  }

  @protected
  SoundRecord sse_decode_sound_record(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    final var_id = sse_decode_i_64(deserializer);
    final var_filepath = sse_decode_String(deserializer);
    final var_filename = sse_decode_String(deserializer);
    final var_duration = sse_decode_f_64(deserializer);
    final var_sampleRate = sse_decode_u_32(deserializer);
    final var_channels = sse_decode_u_16(deserializer);
    final var_format = sse_decode_String(deserializer);
    final var_dateAdded = sse_decode_String(deserializer);
    return SoundRecord(
        id: var_id,
        filepath: var_filepath,
        filename: var_filename,
        duration: var_duration,
        sampleRate: var_sampleRate,
        channels: var_channels,
        format: var_format,
        dateAdded: var_dateAdded);
  }

  @protected
  int sse_decode_u_16(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getUint16();
  }

  @protected
  int sse_decode_u_32(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getUint32();
  }

  @protected
  int sse_decode_u_8(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getUint8();
  }

  @protected
  void sse_decode_unit(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
  }

  @protected
  BigInt sse_decode_usize(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getBigUint64();
  }

  @protected
  int sse_decode_i_32(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getInt32();
  }

  @protected
  bool sse_decode_bool(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getUint8() != 0;
  }

  @protected
  void sse_encode_String(String self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_list_prim_u_8_strict(utf8.encoder.convert(self), serializer);
  }

  @protected
  void sse_encode_audio_fingerprint_info(
      AudioFingerprintInfo self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_f_64(self.duration, serializer);
    sse_encode_f_64(self.spectralCentroid, serializer);
    sse_encode_f_64(self.spectralBandwidth, serializer);
    sse_encode_f_64(self.spectralRolloff, serializer);
    sse_encode_list_prim_f_64_strict(self.mfccMean, serializer);
    sse_encode_list_prim_f_64_strict(self.mfccStd, serializer);
  }

  @protected
  void sse_encode_f_32(double self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putFloat32(self);
  }

  @protected
  void sse_encode_f_64(double self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putFloat64(self);
  }

  @protected
  void sse_encode_i_64(PlatformInt64 self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putPlatformInt64(self);
  }

  @protected
  void sse_encode_list_match_result(
      List<MatchResult> self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    for (final item in self) {
      sse_encode_match_result(item, serializer);
    }
  }

  @protected
  void sse_encode_list_prim_f_32_loose(
      List<double> self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    serializer.buffer.putFloat32List(
        self is Float32List ? self : Float32List.fromList(self));
  }

  @protected
  void sse_encode_list_prim_f_32_strict(
      Float32List self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    serializer.buffer.putFloat32List(self);
  }

  @protected
  void sse_encode_list_prim_f_64_strict(
      Float64List self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    serializer.buffer.putFloat64List(self);
  }

  @protected
  void sse_encode_list_prim_u_8_strict(
      Uint8List self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    serializer.buffer.putUint8List(self);
  }

  @protected
  void sse_encode_list_sound_record(
      List<SoundRecord> self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    for (final item in self) {
      sse_encode_sound_record(item, serializer);
    }
  }

  @protected
  void sse_encode_match_result(MatchResult self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_64(self.soundId, serializer);
    sse_encode_String(self.filepath, serializer);
    sse_encode_String(self.filename, serializer);
    sse_encode_f_64(self.score, serializer);
    sse_encode_f_64(self.matchStart, serializer);
    sse_encode_f_64(self.matchEnd, serializer);
    sse_encode_f_64(self.fileDuration, serializer);
  }

  @protected
  void sse_encode_sound_record(SoundRecord self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_64(self.id, serializer);
    sse_encode_String(self.filepath, serializer);
    sse_encode_String(self.filename, serializer);
    sse_encode_f_64(self.duration, serializer);
    sse_encode_u_32(self.sampleRate, serializer);
    sse_encode_u_16(self.channels, serializer);
    sse_encode_String(self.format, serializer);
    sse_encode_String(self.dateAdded, serializer);
  }

  @protected
  void sse_encode_u_16(int self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putUint16(self);
  }

  @protected
  void sse_encode_u_32(int self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putUint32(self);
  }

  @protected
  void sse_encode_u_8(int self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putUint8(self);
  }

  @protected
  void sse_encode_unit(void self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
  }

  @protected
  void sse_encode_usize(BigInt self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putBigUint64(self);
  }

  @protected
  void sse_encode_i_32(int self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putInt32(self);
  }

  @protected
  void sse_encode_bool(bool self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putUint8(self ? 1 : 0);
  }
}
