// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.11.1.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import 'frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

/// Match result with time range
class MatchResult {
  final PlatformInt64 soundId;
  final String filepath;
  final String filename;
  final double score;
  final double matchStart;
  final double matchEnd;
  final double fileDuration;

  const MatchResult({
    required this.soundId,
    required this.filepath,
    required this.filename,
    required this.score,
    required this.matchStart,
    required this.matchEnd,
    required this.fileDuration,
  });

  @override
  int get hashCode =>
      soundId.hashCode ^
      filepath.hashCode ^
      filename.hashCode ^
      score.hashCode ^
      matchStart.hashCode ^
      matchEnd.hashCode ^
      fileDuration.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is MatchResult &&
          runtimeType == other.runtimeType &&
          soundId == other.soundId &&
          filepath == other.filepath &&
          filename == other.filename &&
          score == other.score &&
          matchStart == other.matchStart &&
          matchEnd == other.matchEnd &&
          fileDuration == other.fileDuration;
}

/// Sound record from database
class SoundRecord {
  final PlatformInt64 id;
  final String filepath;
  final String filename;
  final double duration;
  final int sampleRate;
  final int channels;
  final String format;
  final String dateAdded;

  const SoundRecord({
    required this.id,
    required this.filepath,
    required this.filename,
    required this.duration,
    required this.sampleRate,
    required this.channels,
    required this.format,
    required this.dateAdded,
  });

  @override
  int get hashCode =>
      id.hashCode ^
      filepath.hashCode ^
      filename.hashCode ^
      duration.hashCode ^
      sampleRate.hashCode ^
      channels.hashCode ^
      format.hashCode ^
      dateAdded.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is SoundRecord &&
          runtimeType == other.runtimeType &&
          id == other.id &&
          filepath == other.filepath &&
          filename == other.filename &&
          duration == other.duration &&
          sampleRate == other.sampleRate &&
          channels == other.channels &&
          format == other.format &&
          dateAdded == other.dateAdded;
}
